server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hzhiping/microservicecloud-config.git #GitHub上面的git仓库名字
          basedir: /Users/hzhiping/git-repo/microservicecloud-config
          default-label: main

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'