server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hzhiping/cloud-config.git # GitHub 上面的 git 仓库名字
          basedir: /Users/hzhiping/git-repo/cloud-config
          default-label: main

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'